# Generated by Django 2.2.3 on 2019-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KatLog_Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=20)),
                ('Body', models.TextField()),
                ('Image', models.ImageField(height_field=500, max_length=2, upload_to='MediaLib', width_field=500)),
                ('Source', models.CharField(max_length=20)),
            ],
        ),
    ]
