# Generated by Django 2.2.3 on 2019-09-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katlog_finance',
            name='Image',
            field=models.ImageField(height_field=500, max_length=1, upload_to='MediaLib', width_field=500),
        ),
    ]
