# Generated by Django 2.2.3 on 2019-09-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190906_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katlog_finance',
            name='Image',
        ),
        migrations.AddField(
            model_name='katlog_finance',
            name='height_field',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='katlog_finance',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='height_field', upload_to='MediaLib', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='katlog_finance',
            name='width_field',
            field=models.IntegerField(default=500),
        ),
    ]
