# Generated by Django 2.2.3 on 2019-09-09 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20190906_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='katlog_finance',
            name='Date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='katlog_finance',
            name='title',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
