# Generated by Django 2.2.3 on 2019-09-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20190910_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='katlog_finance',
            name='Sub_body',
            field=models.CharField(default=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='katlog_finance',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
