# Generated by Django 2.2.3 on 2019-09-13 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20190910_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katlog_finance',
            name='Date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
