# Generated by Django 2.2.3 on 2019-09-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20190918_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katlog_finance',
            name='image',
            field=models.ImageField(upload_to='MediaLib'),
        ),
    ]
