# Generated by Django 2.2.3 on 2019-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20190918_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='katlog_finance',
            old_name='Sub_body',
            new_name='Sub_title',
        ),
        migrations.AddField(
            model_name='katlog_finance',
            name='Sub_Bdy',
            field=models.CharField(default=True, max_length=300),
        ),
    ]
