# Generated by Django 2.2.3 on 2019-09-23 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20190920_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katlog_finance',
            name='Date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
