# Generated by Django 2.2.3 on 2019-09-23 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20190924_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katlog_finance',
            name='Date_posted',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
