# Generated by Django 2.2.3 on 2019-09-23 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20190924_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katlog_finance',
            name='Date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
